package com.oregano.oreganoERP.ui.windows;

import com.oregano.oreganoERP.ui.lists.ContatoList;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.VerticalLayout;

public class TesteWindow extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	@AutoGenerated
	private ContatoList contatoList_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TesteWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setMargin(false);
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		verticalLayout_1.addComponent(horizontalSplitPanel_1);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setMargin(false);
		
		// contatoList_1
		contatoList_1 = new ContatoList();
		contatoList_1.setWidth("-1px");
		contatoList_1.setHeight("-1px");
		contatoList_1.setImmediate(false);
		horizontalSplitPanel_1.addComponent(contatoList_1);
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");
		inlineDateField_1.setImmediate(false);
		horizontalSplitPanel_1.addComponent(inlineDateField_1);
		
		return horizontalSplitPanel_1;
	}

}
